
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# -------------------------------------------------------------------------------------------------------------------------------------------------

sensor:
  - platform: template
    sensors:
      power_in_battery:
        friendly_name: Putere Incarcare Baterie
        unique_id: power_in_battery
        unit_of_measurement: W
        device_class: power
        value_template:  >-
          {% set power = int(states('sensor.victron_system_battery_power')) %}
          {% if power > 0 %} {{ power }}
          {% else %} {{ 0 }}
          {% endif %}
      power_out_battery:
        friendly_name: Putere Descarcare Baterie
        unique_id: power_out_battery
        unit_of_measurement: W
        device_class: power
        value_template:  >-
          {% set power = int(states('sensor.victron_system_battery_power')) %}
          {% if power < 0 %} {{ power | abs }}
          {% else %} {{ 0 }}
          {% endif %}
      power_in_grid:
        friendly_name: Putere In Retea
        unique_id: power_in_grid
        unit_of_measurement: W
        device_class: power
        value_template:  >-
          {% set power = int(states('sensor.victron_system_grid_l1')) %}
          {% if power < 0 %} {{ power | abs }}
          {% else %} {{ 0 }}
          {% endif %}
      power_out_grid:
        friendly_name: Putere Din Retea
        unique_id: power_out_grid
        unit_of_measurement: W
        device_class: power
        value_template:  >-
          {% set power = int(states('sensor.victron_system_grid_l1')) %}
          {% if power > 0 %} {{ power }}
          {% else %} {{ 0 }}
          {% endif %}
  - platform: integration
    source: sensor.pv_power
    name: Energie Produsa
    unique_id: energy_produced
    unit_prefix: k
  - platform: integration
    source: sensor.power_in_battery
    name: Energie Incarcare Baterie
    unique_id: energy_in_battery
    unit_prefix: k
  - platform: integration
    source: sensor.power_out_battery
    name: Energie Descarcare Baterie
    unique_id: energy_out_battery
    unit_prefix: k
  - platform: integration
    source: sensor.power_in_grid
    name: Energie In Retea
    unique_id: energy_in_grid
    unit_prefix: k
  - platform: integration
    source: sensor.power_out_grid
    name: Energie Din Retea
    unique_id: energy_out_grid
    unit_prefix: k

# -------------------------------------------------------------------------------------------------------------------------------------------------

timer:
  door_bell_lock:
    name: Poarta
    icon: mdi:timer

# -------------------------------------------------------------------------------------------------------------------------------------------------

lock:
  - platform: template
    name: Poarta
    unique_id: door_bell
    value_template: "{{ not is_state('timer.door_bell_lock', 'active') }}"
    optimistic: false
    lock:
    unlock:
      - service: dahua_vto.open_door
        data_template:
          entity_id: sensor.door_bell_status
          channel: 1
          short_number: HA

# -------------------------------------------------------------------------------------------------------------------------------------------------

# mqtt:
#   - climate:
#       name: Study
#       modes:
#        - heat
#       object_id: device/thermostat1/temperature
#       unique_id: device/thermostat1/temperature
#       temperature_state_topic: device/thermostat1/temperaturetarget
#       temperature_command_topic: device/thermostat1/temperaturetarget/set
#       current_temperature_topic: device/thermostat1/temperature
#       mode_state_topic: device/thermostat1/mode
#       mode_state_template: heat
#       precision: 0.1
#       temperature_unit: C
#       availability:
#         topic: device/thermostat1/mode
#         value_template: "{%- if value == 'manual' %} online {% else %} offline {% endif -%}"
#   - select:
#       name: Mode
#       object_id: device/thermostat1/mode
#       unique_id: device/thermostat1/mode
#       state_topic: device/thermostat1/mode
#       command_topic: device/thermostat1/mode/set
#       icon: mdi:home-thermometer
#       options:
#         - auto
#         - manual
#         - away
#         - disabled
#   - switch:
#       name: Heat
#       object_id: device/thermostat1/heat
#       unique_id: device/thermostat1/heat
#       state_topic: device/thermostat1/heat
#       command_topic: "device/thermostat1/heat/set



# logger:
#        default: info
#        logs:
#          homeassistant.components.mqtt: debug
